# 모듈(라이브러리)
- 확장자가 .py인 파일
- 변수나 함수 또는 클래스를 모아놓은 파일
- 파이썬 프로그램에서 불러와 사용할 수 있게끔 만들어진 파이썬 파일이라고도 한다.
- Numpy :  고성능 과학계산(고차원 데이터 사용)을 위한 데이터 분석 라이브러리
- Pandas : 행과 열로 구성된 표 형식의 데이터(1,2차원데이터)를 지원하는 라이브러리
- Matplotlib : 2D그래프로 시각화가 가능한 라이브러리

# Numpy
- 빠르고 효율적인 벡터 산술연산을 제공하는 다차원 배열 제공(ndarray 클래스)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학함수(sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

In [1]:
#모듈(라이브러리) 사용하기
import numpy as np

### numpy.ndarray 클래스
- 다차원의 데이터를 저장하는 기능
- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- n 차원 형태로 구성이 가능하다
- 각 값들은 양의 정수로 색인(index)이 부여되어 있다.
- ndarray를 줄여서 array로 표현한다.

In [4]:
#생성하기(1)
#1. 리스트를 먼저 만들어 놓은 후
list1 = [1,2,3,4,5]
list
#2. 리스트를 담는다.
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [5]:
#생성하기(2)
#만듦과 동시에 값을 부여한다.
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
#리스트
#[1,2,3], [4,5,6] 각 요소의 값을 더한다.

In [21]:
#리스트 활용
list1 = [1,2,3]
list2 = [4,5,6]
list3 = []
for i in range(0,3,1) :
    list3.append(list1[i] + list2[i])
list3

[5, 7, 9]

In [24]:
#array 활용
#연산을 진행하면 각 요소끼리 연산을 진행
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [36]:
#2차원 array 생성하기
arr2 = np.array([[1,2,3,], [4,5,6]]) #1차원 요소의 숫자를 동일하게 해야한다 - > 안그러면 크기나 전체요소 개수 확인이 안된다.
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
#array의 크기 확인하기
#shape
arr2.shape # 1차원은 3개씩 있고 2차원은 2개씩 있다

(2, 3)

In [38]:
#array의 전체 요소 개수 확인하기
#size
arr2.size

6

In [39]:
#array의 타입 확인하기
#dtype
arr2.dtype

dtype('int32')

In [40]:
#array의 차원확인하기
#ndim
arr2.ndim

2

In [59]:
#3차원의 array만들고 배열의 크기, 차원, 전체 요소개수 확인
arr3 = np.array( [ [ [1,2], [3,4] ], [[5,6], [7,8] ] ])
arr3
print(f"배열의 크기 : {arr3.shape}")
print(f"배열의 차원 : {arr3.ndim}")
print(f"배열의 전체 요소개수 : {arr3.size}")
print("배열의 크기 : ", arr3.shape)
print("배열의 차원 : ", arr3.ndim)
print("배열의 전체 요소개수 : ",arr3.size)

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 전체 요소개수 : 8
배열의 크기 :  (2, 2, 2)
배열의 차원 :  3
배열의 전체 요소개수 :  8


numpy.ndarray

### 배열 생성하기

In [71]:
#배열 생성하기
# 1. 0값으로 생성하기
# zeros(배열의 크기)
print(np.zeros((3,4)))
# 2. 1값으로 생성하기
#ones(배열의 크기)
print(np.ones((3,4)))
# 3. 지정해서 생성하기
# full(배열의 크기, 채워넣을 값)
np.full((3,4),5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [77]:
# 4. 연속되는 숫자로 배열 생성하기
#arange(시작하는 수, 끝나는 수+1, 간격이 되는 수)
#시작하는 수의 기본값은 0, 간격이 되는 수의 기본값은 1
np.arange(1,51,10)

array([ 1, 11, 21, 31, 41])